name: Build, Test and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      http_proxy: ""
      https_proxy: ""
      no_proxy: "*"

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build and test
        run: |
          podman build -t app-builder -f Dockerfile --target builder .

      - name: Build final image
        run: |
          podman build -t ${{ vars.DOCKERHUB_USERNAME }}/pythod-crud:latest -f Dockerfile .

      - name: Push to Docker Hub
        run: |
          podman login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
          podman push ${{ vars.DOCKERHUB_USERNAME }}/pythod-crud:latest

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    env:
      http_proxy: ""
      https_proxy: ""
      no_proxy: "*"
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            unset http_proxy https_proxy
            podman login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
            podman stop pythod-crud || true
            podman rm pythod-crud || true
            podman rmi ${{ vars.DOCKERHUB_USERNAME }}/pythod-crud:latest || true
            podman pull ${{ vars.DOCKERHUB_USERNAME }}/pythod-crud:latest
            podman run -d --name pythod-crud --network host ${{ vars.DOCKERHUB_USERNAME }}/pythod-crud:latest
